base_url = "https://paulcomte.cafe"
description = "Paul Comte a backend software engineer, Rust, Java and C"
compile_sass = false
minify_html = true
generate_feed = true
default_language = "en"
title = "Paul Comte"

taxonomies = [
    {name = "tags", feed = true},
]

[languages.fr]
weight = 2
languageName = "Français"
languageCode = "fr"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Paul Comte"
display_author = true

favicon = "favicon.ico"
image = ""

default_theme = "dark"
list_pages = false
twitter_card = true

header_nav = [
  { url = "/", name_en = "/home/", name_fr = "/accueil/" },
  { url = "/projects", name_en = "/projects/", name_fr = "/projets/" },
  { url = "/blog", name_en = "/blog/", name_fr = "/blog/" },
  { url = "https://github.com/paulcomte", name_en = "/github/", name_fr = "/github/" },
  { url = "https://www.linkedin.com/in/im-paul-comte", name_en = "/linkedin/", name_fr = "/linkedin/" }
]
